### ISSUE TITLE
[devtools] bring out @emotion's css/keyframe/global 

### ISSUE THREAD

**Issue by fefoweb** [immobiliare/atomic-state#13]
### Feature Request

For better understanding of the code it might be a good solution to bring out @emotion's css/keyframe/global declarations from the various components.

Ex: `devtools/component/LogView.tsx`

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes
| BC Break    | no

#### Summary

This behavior can be seen in `devtools/components/DevToolsPanel.tsx` where all declarations are located upstream of the component: easy to search and possibly modify, without affecting the logic of the component itself.

**Comment by gdorsi** [comment]
Ah thanks for the report!

We will gladly accept a PR to solve this issue :)

**Comment by gdorsi** [comment]
fixed
